interface QRCardProps {
  menuUrl: string
  slug: string
}

export default function QRCard({ menuUrl, slug }: QRCardProps) {
  // QR image generated by api.qrserver.com — no npm package needed
  const qrImageUrl =
    `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(menuUrl)}&size=256x256&color=1C1917&bgcolor=FFFFFF&margin=4&format=png`

  // Download via our proxy route to avoid CORS
  const downloadUrl = `/api/qr-download?data=${encodeURIComponent(menuUrl)}&slug=${encodeURIComponent(slug)}`

  return (
    <div className="bg-white rounded-lg shadow-sm border border-brand-acento p-6 flex flex-col items-center gap-4">
      <h2 className="text-base font-bold text-brand-titulares self-start">
        Tu QR
      </h2>

      {/* QR image */}
      <div className="p-3 border border-brand-acento rounded-lg">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={qrImageUrl}
          alt="QR de tu menú"
          width={200}
          height={200}
        />
      </div>

      {/* Menu URL — clickable link opens menu in new tab */}
      <a
        href={menuUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="w-full flex items-center gap-2 bg-brand-fondo rounded-md px-4 py-3 hover:bg-brand-acento transition-colors duration-150 group"
      >
        <span className="font-mono text-xs text-brand-texto truncate group-hover:text-brand-titulares">
          {menuUrl}
        </span>
      </a>

      {/* Download button — proxied through /api/qr-download */}
      <a
        href={downloadUrl}
        download={`qr-${slug}.png`}
        className="w-full flex items-center justify-center gap-2 bg-brand-principal text-white text-sm font-medium rounded-lg px-4 py-3 min-h-[44px] hover:bg-[#C2410C] focus:outline-none focus:ring-2 focus:ring-brand-principal focus:ring-offset-2 transition-colors duration-150"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
          <polyline points="7 10 12 15 17 10"/>
          <line x1="12" y1="15" x2="12" y2="3"/>
        </svg>
        Descargar QR
      </a>

      {/* Ver mi menú — secondary affordance */}
      <a
        href={menuUrl}
        target="_blank"
        rel="noopener noreferrer"
        className="w-full flex items-center justify-center gap-2 border border-brand-principal text-brand-principal text-sm font-medium rounded-lg px-4 py-3 min-h-[44px] hover:bg-brand-fondo focus:outline-none focus:ring-2 focus:ring-brand-principal focus:ring-offset-2 transition-colors duration-150"
      >
        Ver mi menú
      </a>
    </div>
  )
}
